[phases.setup]
nixPkgs = ["python313", "poetry"]

[phases.install]
cmds = ["poetry install --only main --no-root"]

[phases.build]
cmds = ["echo 'No build phase needed'"]

[start]
cmd = "poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT"
